### ISSUE TITLE
 map pins do not move correctly on map zoom

### ISSUE THREAD

**Issue by monkeydri** [escaladesports/react-store-locator#22]
while zooming/dezooming on the map the pins are not animated in sync with the map, instead they seem to be re-rendered once map zoom is completed.

Also they are translated to their new positions from top left (on dezoom) or bottom right (on zoom), this does not look really nice.

visible on the demo : https://react-store-locator-demo.netlify.com/

any way to make it look better ?

**Comment by tbaustin** [comment]
I am currently doing a lot of updates and optimizations! It may get fixed during that if not I will directly address it after that. If you want it sooner you could open a PR if you would like :) . I will keep you posted on my progress!

**Comment by monkeydri** [comment]
Nice, yes I started to look for this but it is not a big priority for my current project.

Would you mind sharing what you are working on ? The reason I ask is because I am working on a react-store-locator wrapper which adds location list (panel) on the side (in sync with currently visible pinson the map). Please let me know if you are already working on the same thing ;-)

**Comment by tbaustin** [comment]
I don't think I am currently! For most of the projects I do that separately (side panel). We can add it, but it wouldn't be there by default because that is not really what the map is suppose to do by default! 

If you look at the current issues that is pretty much what I am working on. Some things come up when I work on the issues and may not be documented until they are launched (I know that is bad). But if you have something that you think would help this module please create a PR and as long as it doesn't break the basic functionality i'll add it in :) 

Note: remember we want this to be as basic as possible by default.

**Comment by tbaustin** [comment]
@monkeydri I have done a lot of updating with packages and to the map itself. I do want to not here that this is using google-map-react as the base of the module. I do plan in the distant future to fully pull in google's apis to do this from bottom up, but until then this may not be something I have control over. 

[Here](https://github.com/google-map-react/google-map-react) is the google-map-react module. I do think they have issues open for the markers zooming incorrectly however. I'll leave this issue open, but if no one can find anything in my code to help this then we may just have to wait.

**Comment by monkeydri** [comment]
Thanks for the updates, I will check it out ! I made a couple of changes in my [fork](https://github.com/monkeydri/react-store-locator) (mostly additional data passed on `getValue` callback and use of `AutoComplete` instead of `Search` in search fields so more options can be passed) so I will some time to merge your changes but I will definitely check the google-map-react issue you pointed out.

**Comment by monkeydri** [comment]
I can confirm this has been fixed on latest version 15.4 youhou ! thanks
